In [3]:
import numpy as np

In [4]:
l = np.array([25., 50., 75.,100.])

In [5]:
Sl = np.array([18., 10., 7., 6.])

In [50]:
log_l = np.log(l)
log_Sl = np.log(Sl)

In [51]:
Dr = 4*(np.sum(np.square(log_l))) - np.square(np.sum(log_Sl))

In [52]:
Nr_k = np.sum(log_Sl)*np.sum(np.square(log_l)) - np.sum(log_l)*np.sum(np.multiply(log_Sl,log_l))

In [53]:
Nr_b = -(4*np.sum(np.multiply(log_l,log_Sl)) - np.sum(log_l)*np.sum(log_Sl)) 

In [54]:
log_k = Nr_k/Dr

In [55]:
b = Nr_b/Dr

In [56]:
np.log(100)

4.6051701859880918

In [57]:
log_k

0.13041277081833968

In [58]:
b

0.019260077615282683

In [46]:
S1 = log_k-b*np.log(100)

In [47]:
S1

0.041716835604623248

In [49]:
np.log(6)

1.791759469228055

In [48]:
np.exp(S1)

1.0425992099730215

In [18]:
np.exp(np.log(10))

10.000000000000002

In [104]:
log_l

array([ 3.21887582,  3.91202301,  4.31748811,  4.60517019])

In [105]:
l

array([  25.,   50.,   75.,  100.])

In [106]:
np.log(l)

array([ 3.21887582,  3.91202301,  4.31748811,  4.60517019])

In [107]:
def func(params, xdata, ydata):
    print params
    return (ydata - np.dot(xdata, params))

In [108]:
import scipy.optimize as optimization

In [111]:
xdata = np.transpose(np.array([[1.0,1.0,1.0,1.],
              log_l]))

In [112]:
xdata

array([[ 1.        ,  3.21887582],
       [ 1.        ,  3.91202301],
       [ 1.        ,  4.31748811],
       [ 1.        ,  4.60517019]])

In [113]:
ydata = log_Sl

In [114]:
ydata

array([ 2.89037176,  2.30258509,  1.94591015,  1.79175947])

In [115]:
x0    = np.array([0.0, 0.0])

In [116]:
print optimization.leastsq(func, x0, args=(xdata, ydata))

[ 0.  0.]
[ 0.  0.]
[ 0.  0.]
[  1.49011612e-08   0.00000000e+00]
[  0.00000000e+00   1.49011612e-08]
[ 5.48186441 -0.80959198]
[ 5.48186449 -0.80959198]
[ 5.48186441 -0.80959197]
[ 5.48186442 -0.80959199]
(array([ 5.48186442, -0.80959199]), 3)


In [117]:
np.log(6)

1.791759469228055

In [119]:
np.exp(5.489-0.809*np.log(100))

5.8323343279868967

In [184]:
import numpy as np
import scipy.optimize as optimization
l = np.array([25, 50, 75, 100])
Sl = np.array([18, 10, 7, 6])


log_l = np.log(l)
log_Sl = np.log(Sl)


def func(params, xdata, ydata):
    return (ydata - np.dot(xdata, params))
x0 = np.array([0.0, 0.0])
xdata = np.transpose(np.array([[1.0, 1.0, 1.0, 1.],
                               log_l]))
ydata = log_Sl
log_k, b = optimization.leastsq(func, x0, args=(xdata, ydata))[0]
S = np.exp(log_k + b * np.log(1000)) *10e6

def fwp(wp, wg, D, derivative=False):
    gama = 2600
    F = 1.35
    h = 3.
    a = - 0.36 * S / h
    b =  F * (gama* D) - S * .64
    c =  2 * wg * F * (gama * D)
    d =  (gama * D) * F * wg**2
    if not derivative:
        return (a * wp**3 + b * wp**2 + c * wp + d)
    else:
        return (3 * a * wp**2 + 2 * b * wp + c)

wp1 = 1000
while True:
    wp2 = wp1 - fwp(wp1, 4.5, 200.)/fwp(wp1, 4.5, 200.,True)
    if abs(wp1-wp2) < .00001:
        break
    else:
        wp1 = wp2

print wp1


1.92829232186


In [182]:
S/10e6

0.8952977788164469

In [65]:
import numpy as np
import scipy.optimize as optimization
l = np.array([25, 50, 75, 100])
Sl = np.array([18, 10, 7, 6])


log_l = np.log(l)
log_Sl = np.log(Sl)


def func(params, xdata, ydata):
    return (ydata - np.dot(xdata, params))
x0 = np.array([0.0, 0.0])
xdata = np.transpose(np.array([[1.0, 1.0, 1.0, 1.0],
                               log_l]))
ydata = log_Sl
log_k, b = optimization.leastsq(func, x0, args=(xdata, ydata))[0]
S = np.exp(log_k + b * np.log(1000)) * 1e6


def fwp(wp, wg, D, F, derivative=False):
    roh = 2600
    h = 3.
    g = 9.8
    a = - 0.36 * S / h
    b = F * (roh * g * D) - S * .64
    c = 2 * wg * F * (roh * g * D)
    d = (roh * g * D) * F * wg**2
    if not derivative:
        return (a * wp**3 + b * wp**2 + c * wp + d)
    else:
        return (3 * a * wp**2 + 2 * b * wp + c)

wp1 = 1000
while True:
    wp2 = wp1 - fwp(wp1, 4.5, 1.35, 200.) / fwp(wp1, 4.5, 200., 1.35, True)
    if abs(wp1 - wp2) < .00001:
        break
    else:
        wp1 = wp2

print S / 1e6
print wp1


0.895297778816
67.5209476392


In [66]:
wp_table = np.matrix([[12., 15., 18., 19.5],
                  [13.5, 16.5, 19.5, 21.],
                  [16.5, 19.5, 22.5, 25.5],
                  [22.5, 25.5, 30., 34.5],
                  [28.5, 34.5, 39., 45.],
                  [39., 42., 45., 48.]])

In [67]:
wp_table

matrix([[ 12. ,  15. ,  18. ,  19.5],
        [ 13.5,  16.5,  19.5,  21. ],
        [ 16.5,  19.5,  22.5,  25.5],
        [ 22.5,  25.5,  30. ,  34.5],
        [ 28.5,  34.5,  39. ,  45. ],
        [ 39. ,  42. ,  45. ,  48. ]])

In [68]:
import pandas as pd
I = pd.Index([60., 75., 120., 195., 300., 360.], name="rows")
C = pd.Index([3., 3.6, 4.2, 4.8], name="columns")

In [69]:
df_wp = pd.DataFrame(data=wp_table,index=I,columns=C)

In [70]:
df_F = pd.DataFrame(index=I,columns=C)

In [71]:
def fos(wg, wp, D):
    
for index, rows in df.iterrows():
    D = index
    wg = rows.index[0]
    wp = df.get_value(D,wg)
    

In [56]:
index

60.0

In [64]:
rows.get_value

<bound method Series.get_value of columns
3.0    12.0
3.6    15.0
4.2    18.0
4.8    19.5
Name: 60.0, dtype: float64>